// <auto-generated />
using System;
using GestorAppMotorola;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestorAppMotorola.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20211204195525_App")]
    partial class App
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("AppInstalacion", b =>
                {
                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<int>("InstalacionId")
                        .HasColumnType("int");

                    b.HasKey("AppId", "InstalacionId");

                    b.HasIndex("InstalacionId");

                    b.ToTable("AppInstalacion");
                });

            modelBuilder.Entity("GestorAppMotorola.Modelos.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("App");
                });

            modelBuilder.Entity("GestorAppMotorola.Modelos.Instalacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<bool>("Exitosa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Instalacion");
                });

            modelBuilder.Entity("GestorAppMotorola.Modelos.Operario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<int?>("instalacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("instalacionId");

                    b.ToTable("operario");
                });

            modelBuilder.Entity("AppInstalacion", b =>
                {
                    b.HasOne("GestorAppMotorola.Modelos.App", null)
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestorAppMotorola.Modelos.Instalacion", null)
                        .WithMany()
                        .HasForeignKey("InstalacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorAppMotorola.Modelos.Operario", b =>
                {
                    b.HasOne("GestorAppMotorola.Modelos.Instalacion", "instalacion")
                        .WithMany()
                        .HasForeignKey("instalacionId");

                    b.Navigation("instalacion");
                });
#pragma warning restore 612, 618
        }
    }
}
